export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const LEAD_REPOSITORY = Symbol('LEAD_REPOSITORY');
export const FUNNEL_REPOSITORY = Symbol('FUNNEL_REPOSITORY');
export const FUNNEL_CONTEXT_REPOSITORY = Symbol('FUNNEL_CONTEXT_REPOSITORY');
